### ISSUE TITLE
.NET SDK - Workloads (6.0.400-rtm.22364.21) Checkup... FAILS

### ISSUE THREAD

**Issue by CastleSoft** [unoplatform/uno.check#112]
¤ Uno Platform Check v1.6.0.0 ¤
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────This tool will check your Uno Platform development environment.
If problems are detected, it will offer the option to try and fix them for you, or suggest a way to fix them yourself.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────» Synchronizing configuration... ok
» Scheduling appointments... ok

> OpenJDK 11.0 Checkup...
  - 11.0.12 (C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\..)

> Visual Studio 17.3.0 Checkup...
  - 17.4.0 - C:\Program Files\Microsoft Visual Studio\2022\Community

> Visual Studio Workloads Checkup...
  - Universal Windows Platform development is installed (17.4.0)
  - Mobile development with .NET is installed (17.4.0)
  - ASP.NET and web development is installed (17.4.0)

> Android SDK Checkup...
  - emulator (31.3.11)
  - build-tools;32.0.0 (32.0.0)
  - platforms;android-32 (1)
  - system-images;android-31;google_apis;x86_64 (9)
  - platform-tools (33.0.2)
  - cmdline-tools;5.0 (5.0)

> Android Emulator Checkup...
  - Emulator: pixel_5_-_api_33 found.

> .NET SDK Checkup...
  - 6.0.403 - C:\Program Files\dotnet\sdk\6.0.403
  - 7.0.100 - C:\Program Files\dotnet\sdk\7.0.100

> .NET SDK - Workload Deduplication Checkup...

> Edge WebView2 Checkup...
  - Found Edge WebView2 version 107.0.1418.35

> Windows Subsystem for Linux Checkup...
  - Ubuntu (Default)
  - Ubuntu-22.04

> Windows Phyton Installation Checkup Checkup...
  - Python is installed in C:\Windows\.

> Windows Long Path Checkup Checkup...
  - Long paths are enabled on Windows!

> Windows Hyper-V Checkup Checkup...
  - Hyper-V is configured

> .NET SDK - Workloads (6.0.400-rtm.22364.21) Checkup...
  × android (Microsoft.NET.Sdk.Android.Manifest-6.0.300 : 32.0.448/6.0.400) not installed.
  × ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.400 : 15.4.446-ci.-release-6-0-4xx.446/6.0.400) not installed.
  × maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400 : 15.4.446-ci.-release-6-0-4xx.446/6.0.400) not installed.
  × macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.400 : 12.3.446-ci.-release-6-0-4xx.446/6.0.400) not installed.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
¤ Recommendation: Install or Update SDK Workloads
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

! Attempt to fix? [y/n] (y): y
» Attempting to fix: .NET SDK - Workloads (6.0.400-rtm.22364.21)
SHELL: C:\Program Files\dotnet\dotnet.exe workload install --from-rollback-file "C:\Users\andrew\AppData\Local\Temp\maui-check-a24313b2\workload.json" android ios maccatalyst macos --source "https://api.nuget.org/v3/index.json"

Workload(s) 'android ios maccatalyst macos' are already installed.
Warning: Workload garbage collection failed with error: An item with the same key has already been added. Key: (Microsoft.NETCore.App.Runtime.Mono.android-arm, 6.0.11).

Successfully installed workload(s) android ios maccatalyst macos.

Fix applied.  Checking again...

> .NET SDK - Workloads (6.0.400-rtm.22364.21) Checkup...
  � android (Microsoft.NET.Sdk.Android.Manifest-6.0.300 : 32.0.448/6.0.400) not installed.
  � ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.400 : 15.4.446-ci.-release-6-0-4xx.446/6.0.400) not installed.
  � maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400 : 15.4.446-ci.-release-6-0-4xx.446/6.0.400) not installed.
  � macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.400 : 12.3.446-ci.-release-6-0-4xx.446/6.0.400) not installed.

� Recommendation: Install or Update SDK Workloads

! Attempt to fix? [y/n] (y): y

! There were one or more problems detected.
Please review the errors and correct them and run uno-check again.

**Comment by jeromelaban** [comment]
Thanks for the report. We're about to be publishing an updated build of Uno.Check that supports 17.4 (https://github.com/unoplatform/uno.check/pull/111). 

In the meantime, you can update to the latest prerelease build with `dotnet update uno.check --version "1.9.0-dev.8"`, then run `uno-check --pre` to install for VS 17.4.

**Comment by TiMeJuMp** [comment]
the command for updating globaly is `dotnet tool update -g uno.check --version "1.9.0-dev.8"`otherwise you get some errors.

**Comment by jeromelaban** [comment]
Fixed in uno.check 1.10
