### ISSUE TITLE
Execute uno.check without elevated privileges.

### ISSUE THREAD

**Issue by ADD-David-Antolin** [unoplatform/uno.check#113]
Currently executing uno-check triggers an elevated privileges prompt. 

I don't know if elevated privileges are really necessary unless the user answers 'yes' to the attempt to fix questions. If it is not necessary, could be an argument added to run without elevated privileges? 

We are in a constrained security machines and before calling someone with elevated privileges to fix the errors it would be great to know if there is anything to fix.

**Comment by jeromelaban** [comment]
Thanks for the report. At this time, running elevated is required as many steps alter system settings or protected folders.

That being said, if you still want to run it without, you can use the following:

```
cmd /c "set __COMPAT_LAYER=RUNASINVOKER && uno-check"
```

**Comment by ADD-David-Antolin** [comment]
Thank you, it is good enough for now.

**Comment by jeromelaban** [comment]
Documented in https://github.com/unoplatform/uno.check/pull/114
