### ISSUE TITLE
dotnet workload install wasm-tools-net6 vs uno-check

### ISSUE THREAD

**Issue by CastleSoft** [unoplatform/uno.check#158]
Installing 

dotnet workload install wasm-tools-net6

...
Removing Microsoft.Android.Ref.33.33.0.4-x64.msi ..... Done
Removing Microsoft.Android.Runtime.33.android-arm.33.0.4-x64.msi ..... Done
Removing Microsoft.Android.Runtime.33.android-arm64.33.0.4-x64.msi ..... Done
Removing Microsoft.Android.Runtime.33.android-x64.33.0.4.msi ..... Done
Removing Microsoft.Android.Runtime.33.android-x86.33.0.4-x64.msi ..... Done
Removing Microsoft.Android.Sdk.Windows.32.0.476-x64.msi ........... Done
Removing Microsoft.Android.Sdk.Windows.33.0.4-x64.msi ........... Done
Removing Microsoft.Android.Templates.33.0.4-x64.msi .... Done
Removing Microsoft.macOS.Ref.12.3.0.2372-x64.msi ..... Done
Removing Microsoft.macOS.Runtime.osx-arm64.12.3.0.2372-x64.msi ..... Done
Removing Microsoft.macOS.Runtime.osx-x64.12.3.0.2372.msi ..... Done
Removing Microsoft.macOS.Sdk.12.3.0.2372-x64.msi ...... Done
Removing Microsoft.macOS.Sdk.12.3.471.471-x64.msi ...... Done
Removing Microsoft.macOS.Templates.12.3.0.2372-x64.msi .... Done
....

uno-check
....
> .NET SDK - Workloads (7.0.100) Checkup...
  × android (Microsoft.NET.Sdk.Android.Manifest-7.0.100 : 33.0.4/7.0.100) not installed.
  × ios (Microsoft.NET.Sdk.iOS.Manifest-7.0.100 : 16.0.1478/7.0.100) not installed.
  × maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100 : 15.4.2372/7.0.100) not installed.
  × macos (Microsoft.NET.Sdk.macOS.Manifest-7.0.100 : 12.3.2372/7.0.100) not installed.
  
  ......
  
  Attempt to fix (Y)
...
Installing Microsoft.NET.Sdk.Android.Manifest-7.0.100.33.0.4-x64.msi ..... Done
Installing Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.0.1478-x64.msi ..... Done
Installing Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.15.4.2372-x64.msi ..... Done
Installing Microsoft.NET.Sdk.macOS.Manifest-7.0.100.12.3.2372-x64.msi .... Done
Installing Microsoft.Android.Sdk.Windows.33.0.4-x64.msi .............. Done
Installing Microsoft.Android.Sdk.Windows.32.0.476-x64.msi ............. Done
Installing Microsoft.Android.Ref.33.33.0.4-x64.msi ...... Done
Installing Microsoft.Android.Runtime.33.android-arm.33.0.4-x64.msi ...... Done
Installing Microsoft.Android.Runtime.33.android-arm64.33.0.4-x64.msi ...... Done
Installing Microsoft.Android.Runtime.33.android-x86.33.0.4-x64.msi ...... Done
Installing Microsoft.Android.Runtime.33.android-x64.33.0.4.msi ...... Done
Installing Microsoft.Android.Templates.33.0.4-x64.msi .... Done
Installing Microsoft.macOS.Sdk.12.3.0.2372-x64.msi ..... Done
Installing Microsoft.macOS.Sdk.12.3.471.471-x64.msi ..... Done
Installing Microsoft.macOS.Ref.12.3.0.2372-x64.msi ..... Done
Installing Microsoft.macOS.Runtime.osx-x64.12.3.0.2372.msi ...... Done
Installing Microsoft.macOS.Runtime.osx-arm64.12.3.0.2372-x64.msi ...... Done
Installing Microsoft.macOS.Templates.12.3.0.2372-x64.msi .... Done
...
  
  
  Which is correct ? wasm-tools-net6  / uno-check ? Each installes/removes the other ?
  
  Thanks

**Comment by jeromelaban** [comment]
Thanks for the report. This behavior is defined by the .NET SDK itself and we do not have control over it. uno-check runs `dotnet install android ios maccatalyst macos` with specific versions, and the removal of the android tooling may be a bug of the `wasm-tools-net6` workload or in the SDK itself.

Try running both commands manually to determine which is doing what, and try to report a bug in the `dotnet/sdk` repository.
