### ISSUE TITLE
VS 17.8.0 Preview 1.0 Fix Failed!

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno.check#160]
Hi,

After upgrading Visual Studio Enterprise 2022 from version 17.7.0 Preview 5.0 to 17.8.0 Preview 1.0, the following error occurs when trying to resolve some bugs in the workload checking section.

![image](https://github.com/unoplatform/uno.check/assets/3469909/180937d9-c53a-4b4c-b234-b519662ac29f)

Thanks!

**Comment by Suriman** [comment]
This error does not occur when migrating the stable version, from 17.6.5 to 17.7.0

**Comment by jeromelaban** [comment]
Thanks for the report. By the looks of your installation, you only have .NET 8 installed, is that correct? If that's the case, uno-check without paramters may not work properly, thought it should have been trying to install .NET 7.0.30x, which is not the case here.

Can you try running with `uno-check --pre-major` instead? Thanks!

**Comment by Suriman** [comment]
Hi, after running the suggested command, the same error still occurs.
![image](https://github.com/unoplatform/uno.check/assets/3469909/0fa1aa18-82b8-44c6-b5a4-e44a9a619440)

**Comment by jeromelaban** [comment]
Thanks for the update. The issue is fixed by https://github.com/unoplatform/uno.check/pull/162 and available in Uno.Check 1.14.0 (available momentarily on nuget.org).
