### ISSUE TITLE
Error: No such host is known. (raw.githubusercontent.com:443)

### ISSUE THREAD

**Issue by irvnriir** [unoplatform/uno.check#171]
This is all im getting
```
? Could not check for latest version of uno-check on NuGet.org. The currently installed version may be out of date.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Would you still like to continue with the currently installed version? [y/n] (n): y
> Synchronizing configuration...Error: No such host is known. (raw.githubusercontent.com:443)
```

I tried to run DNS lookup, it succeeded for `raw.githubusercontent.com` and failed for `raw.githubusercontent.com:443` .

**Comment by jeromelaban** [comment]
Thanks for the report. This looks like a local issue for your machine, transient maybe? Can you try again and let us know?

**Comment by irvnriir** [comment]
@jeromelaban it've been since a version half a year ago

**Comment by jeromelaban** [comment]
Thanks, to be sure, you have always been having this specific error for 6 months? Does it happen if you update uno check with `dotnet tool update -g uno.check` ?

**Comment by irvnriir** [comment]
@jeromelaban this post is under scope of current version

**Comment by jeromelaban** [comment]
Thanks. Does it work on any other machines you have available?

Still, this is a very curious error, for which the resolution is likely to not be in this tool.

The code doing the fetch is located here:

https://github.com/unoplatform/uno.check/blob/8b3b649da8658ee6bea057b8bf7d7bfe4d348afd/UnoCheck/Manifest/Manifest.cs#L31-L32

It's very simple, and uses only .NET APIs.

Are you able to run this code in a simple .NET 7 console app on your system:

```csharp
var http = new HttpClient();
var json = await http.GetStringAsync("https://raw.githubusercontent.com/unoplatform/uno.check/f20a61715347d754d957c986438d2e96fc14ac5a/manifests/uno.ui.manifest.json");
Console.WriteLine(json);
```

**Comment by irvnriir** [comment]
HttpClient 's funcs cause the request to be sent and received by server, but before providing output, error with:
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ac_DotNet.<f1>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
* i couldn't find any info in Windows Events, though i could miss it .

the issue seems to be caused by that some servers mess up the response (maybe by outdated standard, but still) and its rejected by OS API which .NET uses .

workaround, not intended for release

* GetStringAsync works after

	```
		var netAssembly = Reflection.Assembly.GetAssembly(typeof(System.Net.Configuration.SettingsSection));
		if (netAssembly != null) {
			var bindingFlags = Reflection.BindingFlags.Static | Reflection.BindingFlags.GetProperty | Reflection.BindingFlags.NonPublic;
			var settingsType = netAssembly.GetType("System.Net.Configuration.SettingsSectionInternal");
			
			var instance = settingsType.InvokeMember("Section", bindingFlags, null, null, new object[0]);
			
			if (instance != null) {
				bindingFlags = Reflection.BindingFlags.NonPublic | Reflection.BindingFlags.Instance;
				var UseUnsafeHeaderParsing = settingsType.GetField("useUnsafeHeaderParsing", bindingFlags);
				if (UseUnsafeHeaderParsing != null) {
					UseUnsafeHeaderParsing.SetValue(instance, true);
				} else {Console.Write("#unexpected");}
			} else {Console.Write("#unexpected");}
		} else {Console.Write("#unexpected");}
	```
	* credits: https://blog.hildenco.com/2017/12/powershell-server-committed-protocol.html
	
correct solution would be using: other implementation of SocketsHttpHandler/HttpClientHandler, analog of HttpClient, other server setup, or other protocol than HTTP .

**Comment by irvnriir** [comment]
actually, another, and the most important, self-sufficient part of the complete solution is to include all required content into the app package or as Nuget dependencies .

**Comment by jeromelaban** [comment]
This is an interesting analysis, though you're the first to experience this issue even if all other of Uno Check users that don't experience it.

A few thoughts:
- Which version of .NET SDK do you have installed on your machine ? (`dotnet --list-sdks` can tell) 
- Do you have a specific version of Windows?
- In a specific windows security mode maybe?
- A proxy or transparent proxy that modifies contents or DNS queries?
- Have you tried on another machine or network?

I'm having trouble thinking that a largely used service like github raw content would respond with outdated specs, given that it's used in extremely large number of other ecosystems tooling that would fail similarly.

**Comment by irvnriir** [comment]
i meant the protocol which it doesn't satisfy is outdated, its Win10

**Comment by irvnriir** [comment]
is there update on this ?

**Comment by jeromelaban** [comment]
I don't think we'll be able to fix this issue by means of what your describing, particularly if we cannot reproduce on our end.

That being said you can use the `--manifest c:\temp\uno.ui.manifest.json` parameter and [download the manifest file](https://raw.githubusercontent.com/unoplatform/uno.check/main/manifests/uno.ui.manifest.json) manually and start from there.

**Comment by irvnriir** [comment]
this is all thats needed, ty .
