### ISSUE TITLE
Remove requirement for Visual Studio for Mac

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno.check#173]
> 🔎 Visual Studio 8.10.0 Checkup...
>  ✔ Visual Studio for Mac (17.6.0.1575)

It is not needed and occupy nearly 2GB of disk space.

**Comment by carlh98** [comment]
@nickrandolph @spouliot 
Just to confirm, Visual Studio for Mac is optional in Uno Check, we need to remove all together?
