### ISSUE TITLE
Add support for detecting VS Build Tools installation

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno.check#188]
In Uno-Check version 1.16.1.0 and earlier, the installation of Visual Studio Build Tools is not properly detected, indicating that Visual Studio is not installed. That's correct, Visual Studio is not installed but the Build Tools are and we think that the Uno-Check tool should not give an warning, but simply indicate that what is installed are the Build Tools, since a machine with the Build Tools compiles correctly Uno Platform applications.

![image](https://github.com/unoplatform/uno.check/assets/3469909/70b0a6c3-fe96-4693-99d0-487f6be1a077)

Continue ...

![image](https://github.com/unoplatform/uno.check/assets/3469909/f4261a47-a1dc-402f-ae40-c8f2ce04a479)

In addition, they also indicate that the workloads are not installed, when in fact they are:

![image](https://github.com/unoplatform/uno.check/assets/3469909/e478aa26-cbb8-4d57-8ee4-f40011710257)

**Comment by jeromelaban** [comment]
@Suriman on this particular issue, where are you running uno.check? Is it on a CI environment? If so, you can skip the check for visual studio using `--skip vswinworkloads` and `--skip vswin`.

**Comment by Suriman** [comment]
@jeromelaban Thank you very much for the information, it is just what we needed.
