### ISSUE TITLE
Adjust architecture checks on macOS

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.check#192]
![image](https://github.com/unoplatform/uno.check/assets/1075116/fedd4c3d-816a-4637-b167-cb8da4575c5c)

**Comment by MartinZikmund** [comment]
We should check for x86 on macOS devices that are Intel based, but skip this on Mx Macs

**Comment by jeromelaban** [comment]
Skipping is not the way to go, we really need to install the arm64 version of the images. It's likely that the .NET runtime is running in rosetta and not reporting the actual CPU architecture.

**Comment by spouliot** [comment]
> It's likely that the .NET runtime is running in rosetta and not reporting the actual CPU architecture.

Yes, here's what I get with the latest (1.17.0.0) `uno-check`

```
🔎 Android SDK Checkup...
  ✔ emulator (31.2.10)
  ❌ build-tools;34.0.0 (34.0.0) missing.
  ❌ platforms;android-34 (1) missing.
  ❌ system-images;android-34;google_apis;arm64-v8a (6) missing.
  ✔ platform-tools (33.0.2)
  ✔ cmdline-tools;5.0 (5.0)
```

and I'm running the arm64 version of dotnet

```bash
which dotnet
/usr/local/share/dotnet/dotnet

file /usr/local/share/dotnet/dotnet
/usr/local/share/dotnet/dotnet: Mach-O 64-bit executable arm64
```

Maybe we could detect/warn if the _incorrect_ (`x86_64` on `arm64` using Rosetta) version of `dotnet` is being used to run `uno-check` ?

**Comment by jeromelaban** [comment]
@spouliot I've changed this in latest so that the system images are arm64, and it seemed to work for me. Are you seeing something else that does not work?

**Comment by jeromelaban** [comment]
Fixed in 1.17

**Comment by spouliot** [comment]
> Are you seeing something else that does not work?

No this worked for me, but I did not try to run `dotnet` as a x86-64 binary

**Comment by spouliot** [comment]
If I install `uno.check` 1.17.0.0 with the `x86-64` version of `dotnet` then execute it, then I get

```
🔎 Android SDK Checkup...
  ✔ emulator (31.2.10)
  ❌ build-tools;34.0.0 (34.0.0) missing.
  ❌ platforms;android-34 (1) missing.
  ❌ system-images;android-34;google_apis;x86_64 (6) missing.
  ✔ platform-tools (33.0.2)
  ✔ cmdline-tools;5.0 (5.0)
```

which is not optimal on an arm64 Mac computer, hence a warning about this condition might be useful.

**Comment by spouliot** [comment]
```bash
/usr/local/share/dotnet/x64/dotnet tool update --global Uno.Check
```

This does not happen after I installed the `system-images;android-34;google_apis;arm64-v8a` with the `arm64` version of `uno-check`. 

IOW going back to `x86-64` version of `dotnet` does not cause `uno-check` to report `system-images;android-34;google_apis;x86_64 (6) missing.` and everything is green.

There must be a check that will suggest the later when some things in Android SDK are missing.
