### ISSUE TITLE
CI `uno-check` fails with "Invalid long option name"

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.check#193]
## Current behavior

When running the `action.yml` generated by the GitHub actions uno.templates template, I get:

```
You can invoke the tool using the following command: uno-check
Tool 'uno.check' (version '1.16.2') was successfully installed.

Error: Invalid long option name.

       check -v --ci --non-interactive --fix --target all
                                                     ^ Invalid character

Error: Process completed with exit code 1.
```

## Expected behavior

Should not fail

## How to reproduce it (as minimally and precisely as possible)

Create blank uno app template with .NET 8 with all targets and GH Actions CI option

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This feels like any CLI tool would fail for a character issue like this. Do you know which character that was?

**Comment by DenisZhukovski** [comment]
@jeromelaban if you replace $targets injection with direct call everything is working well, the problem occurs when
if ($targets.Contains("all")) {
   $targets = "--target all"       
}
executed

**Comment by DenisZhukovski** [comment]
@jeromelaban @MartinZikmund working code
("${{ inputs.target-platform }} ".Split(' ') | ForEach-Object {
          $target = $_.Replace("_win", "").Replace("_macos", "")
          if (![string]::IsNullOrEmpty($target)) {
            echo "target: $target" 
            uno-check -v --ci --non-interactive --fix --target $target --skip xcode
            echo "uno-check finished for target: $target " 
          }
        })

**Comment by MartinZikmund** [comment]
@DenisZhukovski do you want to contribute a PR for this?

**Comment by jeromelaban** [comment]
@DenisZhukovski you can fork this repo, make the changes then push a PR to this repo. Thanks!

**Comment by MartinZikmund** [comment]
@DenisZhukovski this walkthrough may be useful - https://github.com/firstcontributions/first-contributions

**Comment by DenisZhukovski** [comment]
https://github.com/unoplatform/uno.templates/pull/583

From: Martin Zikmund ***@***.***>
Date: Tuesday, 27 February 2024 at 14:41
To: unoplatform/uno.check ***@***.***>
Cc: Dzianis Zhukouski ***@***.***>, Mention ***@***.***>
Subject: Re: [unoplatform/uno.check] CI `uno-check` fails with "Invalid long option name" (Issue #193)

@DenisZhukovski<https://urldefense.com/v3/__https:/github.com/DenisZhukovski__;!!GF_29dbcQIUBPA!yt7qrW_47TPKKEdboAlSSAuWeBjzDTjypxTMK1rEr59blsPJ99R62BP6lm_T1nWtUmouMuN6-t3W47oVnepZ_YoZh_46SPk$> this walkthrough may be useful - https://github.com/firstcontributions/first-contributions<https://urldefense.com/v3/__https:/github.com/firstcontributions/first-contributions__;!!GF_29dbcQIUBPA!yt7qrW_47TPKKEdboAlSSAuWeBjzDTjypxTMK1rEr59blsPJ99R62BP6lm_T1nWtUmouMuN6-t3W47oVnepZ_YoZ2a8RmaM$>
