### ISSUE TITLE
Android Check Fails

### ISSUE THREAD

**Issue by jguadagno** [unoplatform/uno.check#20]
When running v1.0.2.0 I get the following message

> ! There were one or more problems detected.
Please review the errors and correct them and run uno-check again.

As shown here:
<img width="615" alt="unocheck" src="https://user-images.githubusercontent.com/3209610/144166074-0877f4d5-9f89-432c-b159-6ac8ad83b165.png">

However, there are no error messages.

When I run `uno-check --verbose` I get the following response.

[unocheck-verbose.txt](https://github.com/unoplatform/uno.check/files/7630531/unocheck-verbose.txt)

You will see an error during the `Android Emulator Checkup...`

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at DotNetCheck.AndroidSdk.AvdManager.ListAvds() in /_/UnoCheck/AndroidSdk/AvdManager.cs:183
  at DotNetCheck.Checkups.AndroidEmulatorCheckup.Examine(SharedState history) in /_/UnoCheck/Checkups/
     AndroidEmulatorCheckup.cs:51
  at DotNetCheck.Cli.CheckCommand.ExecuteAsync(CommandContext context, CheckSettings settings) in /_/UnoCheck/
     CheckCommand.cs:167
```

Is Uno.Check expecting the emulators in a certain folder?

**Comment by jeromelaban** [comment]
By the looks of it, it's supposed to be there:
https://github.com/unoplatform/uno.check/blob/c4864d84857229516edd03cd2a1383ef63d36206/UnoCheck/Checkups/AndroidEmulatorCheckup.cs#L50, though by the looks of the exception, it looks like the contents of the document returned by googles AVD listing misses a `name` property somehow.

**Comment by jguadagno** [comment]
@jeromelaban I stepped through the code and determined what the issue is.  It's a combination of assumptions that the code makes and my *Android* configuration for a particular AVD.

Looking at the following code: 
https://github.com/unoplatform/uno.check/blob/c4864d84857229516edd03cd2a1383ef63d36206/UnoCheck/AndroidSdk/Avd.cs#L39-L40

The variables `avdIniFile` and `configIniFile` are set based on the folder names of the AVD files.

On my machine where I ran `uno-check`, I have two AVDs set up.

* '**Pixel 4 API 30**' in folder `Pixel 4 API 30.avd`
* '**ReactNative**' in folder `ReactNative_Test.avd`

As a result, line 39
https://github.com/unoplatform/uno.check/blob/c4864d84857229516edd03cd2a1383ef63d36206/UnoCheck/AndroidSdk/Avd.cs#L39
is created as `<path>\ReactNative_Test.ini` which doesn't exist.

One solution would be to use the value `AvdId` from the `config.ini`. This would mean the `config.ini` would need to be parsed first to determine the id of the AVD so that you could determine the correct *<avd_name>.ini* file.

 I could try and reorganize the `From` method if you would like. It would just have to wait until the end of next week.

**Comment by jeromelaban** [comment]
Thanks for the investigation! Did you create the ReactNative_Test emulator in any particular way ?

**Comment by jguadagno** [comment]
From what I remember... yes...

```
avdmanager create avd --force --name ReactNative --abi google_apis/x86 --package "system-images;android-29;google_apis;x86_64" --device "pixel_xl" --path c:\Android\AVDs
```

Honestly, I don't remember how I got the _Test... I may have originally named it `ReactNative_Test` while I was figuring it out and then renamed it.
