### ISSUE TITLE
Improve Windows ARM Support

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno.check#200]
When running Uno-Check from a Windows Arm PC, it failes to fix some tasks like installing a dotnet SDK. 

It downloads the SDK and supossely install it, but in fact it is not.

<img width="1592" alt="uno-check-winarm-dotnet-checkup" src="https://github.com/unoplatform/uno.check/assets/1900897/457ca0af-3ccb-4745-ab3d-776cb1f41ab4">

**Comment by jeromelaban** [comment]
Merged in latest
