### ISSUE TITLE
Xcode not found (Xcode 15.0.1) with Uno Check

### ISSUE THREAD

**Issue by stefandevo** [unoplatform/uno.check#213]
### Current behavior

The latest (stable) version of Xcode is 15.0.1 (https://xcodereleases.com)

When running Uno Check, while updated through AppStore to latest version, gives

XCode 15A240d Checkup...
  ❌ Xcode.app (15.0 15A240d) not installed.

💉 Recommendation: Download XCode 15.0 15A240d

### Expected behavior

It finds the latest stable version.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks for the report. We have yet to publish a stable update of uno.check that fixes this particular case, but you should be able to to test this by installing the latest preview (fixed by https://github.com/unoplatform/uno.check/pull/206):

```
dotnet new install -g uno.check --version 1.18.0-dev.12
```
