### ISSUE TITLE
Python detection

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno.check#249]
When installing python using VS installer, it's seems to not being registered in the PATH, but uno-check still detects it properly:

![image](https://github.com/unoplatform/uno.check/assets/8635919/60f8acc0-ef4d-40b4-832e-7162575f8777)

but then WASM build is failing:

![image](https://github.com/unoplatform/uno.check/assets/8635919/51d7693c-9cf5-42a3-aa1a-c2a49de1ab33)

**Comment by jeromelaban** [comment]
Not needed anymore with net9
