### ISSUE TITLE
Incorrect Sentence Start in Uno.Check Tool Output for dotnet new Uno Templates Checkup

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.check#277]
When running the uno.check tool, an incorrect sentence start is observed in the output for the command line templates checkup. Specifically, **", latestndation:"** appears instead of a correctly structured sentence.

![uno sdk](https://github.com/user-attachments/assets/4273da75-1e4e-4f87-b32a-c9a06141b0ad)

**Uno.Check version: 1.25.1**

**Comment by morning4coffe-dev** [comment]
@agneszitte @jeromelaban This seems to be similar to https://github.com/unoplatform/uno.check/issues/236. I was planning to take a look into the issue, but seems like the text generated is not the same for everyone
