### ISSUE TITLE
Error creating an Android Emulator

### ISSUE THREAD

**Issue by chrisdreams13** [unoplatform/uno.check#38]
I installed and run the app as you suggest, installed so many missing thing, and created an avd. I don't know what happen but failed.

![image](https://user-images.githubusercontent.com/6045302/159082457-585507df-c253-487c-8649-e26badbe9079.png)

Running again with verbose throws this error:

> Android Emulator Checkup...
System.NullReferenceException: Object reference not set to an instance of an object.
  at DotNetCheck.AndroidSdk.AvdManager.ListAvds() in /_/UnoCheck/AndroidSdk/AvdManager.cs:183
  at DotNetCheck.Checkups.AndroidEmulatorCheckup.Examine(SharedState history) in /_/UnoCheck/Checkups/
     AndroidEmulatorCheckup.cs:51
  at DotNetCheck.Cli.CheckCommand.ExecuteAsync(CommandContext context, CheckSettings settings) in /_/UnoCheck/
     CheckCommand.cs:167

Checking the code I found that the AVD was created in the admin profile: 'C:\Users\admin\\.android\avd\Android_Emulator_31.avd', but there are only 3 files ([avd.zip](https://github.com/unoplatform/uno.check/files/8307626/avd.zip)) but no error in verbose mode. I guess the problem is that the avd is incomplete.

Please add the possibility to pass a user that contains my avd 'C:\Users\florencia\\.android\avd\Pixel_2_API_27.avd' or fix the problem creating your own one. 

Note: Copying my user avd to admin folder works ok, but should not be the best option. Creating a shortcut to my user no works.

**Comment by jeromelaban** [comment]
Fixed in latest builds
