### ISSUE TITLE
Add validation for Hyper-V on Windows

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.check#46]
This is required to get fast performing Android emulators.

Validate that either HAXM or Hyper-V is installed (https://github.com/unoplatform/uno.check/issues/46#issuecomment-1099614653)

**Comment by agneszitte-nventive** [comment]
It would be great if uno-check can do the primarily checks for Hyper-V support (systeminfo) and HAXM support if needed (sc query intelhaxm) in addition to check if everything is correctly installed after depending of what is supported.
