### ISSUE TITLE
Android emulator validation fails

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.check#48]
Currently, the Android SDK installer validation fails with the following error:

```
System.Xml.XmlException: ''en' is an unexpected token. The expected token is '"' or '''. Line 3, position 12.'
```
when the download of this resource fails with a 404:
```
https://dl.google.com/android/repository/sys-img/android-desktop/sys-img2-3.xml
```
This url is provided by this manifest, and seems to be incorrectly provided by Google's servers:
```
https://dl.google.com/android/repository/addons_list-5.xml
```

This may be a temporary issue, let's give it a few days to resolve itself.

## Manual SDK Installation
Install the Android SDK 31 and 32 manually, following the instructions here https://aka.ms/dotnet-androidsdk-help.

## Workaround
Add the following parameter to uno-check `--skip androidemulator --skip androidsdk`

**Comment by bvillagran** [comment]
Not posting for help, just providing information for your troubleshooting.

Fairly clean Win10 installation, not previously installed any SDK's or VS

Installed everything as per (my preferred editor is VS Code so I set that up first if I want to use it).
https://platform.uno/docs/articles/get-started-vscode.html

uno-check - Got errors about WSL, installed WSL, then got errors about Android SDK and did a complete environment setup as per https://platform.uno/docs/articles/get-started-vs-2022.html#

Installed the Android SDK 31 Manually (Didn't see option for SDK 32), and cloned the Uno main repository and opened the Uno.UI solution, did all other installations of older .NET SDK's and packages that the projects were targeting

uno-check - Says everything is good but warns about Android SDK still. Output: https://gist.github.com/bvillagran/6dce748c040ba9b05f975ced5437504e

**Comment by jeromelaban** [comment]
Thanks for the updates. The android SDK is still failing, it's in Google's hands for now: https://issuetracker.google.com/issues/229992980

**Comment by jeromelaban** [comment]
Fixed by google a few hours ago.
