### ISSUE TITLE
uno.check 1.4.0-dev.5 is installing mono 6.04 and Visual studio 2022 preview 17.3 needs mono 6.05

### ISSUE THREAD

**Issue by cesarchefinho** [unoplatform/uno.check#62]
with mono 6.04 installed by uno-check I cannot start an android application.

The error message is ...  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "mono_opt_aot_lazy_assembly_load" referenced ...

editing workload.json from temp dir and changing "microsoft.net.workload.mono.toolchain":  from 6.04 to "6.0.5"  and calling dotnet workload install --from-rollback-file workload.json android ios maccatalyst tvos macos wasm-tools wasm-tools --source "https://api.nuget.org/v3/index.json" --source "https://aka.ms/dotnet6/nuget/index.json" fixes it

**Comment by jeromelaban** [comment]
Thanks for the update, this was fixed in https://github.com/unoplatform/uno.check/pull/61, but not published by default. A new release will be out soon.
