### ISSUE TITLE
uno-check fails silently when Xcode is not installed

### ISSUE THREAD

**Issue by Wave-SYJ** [unoplatform/uno.check#71]
I was following the guide [Get Started on JetBrains Rider](https://platform.uno/docs/articles/get-started-rider.html?tabs=macos) and ran the command `uno-check --pre`, then I got:

<img width="647" alt="图片" src="https://user-images.githubusercontent.com/56124108/171005635-efb6f3a0-3757-415f-be82-e47dd76aa394.png">

It seemed that no problem was found but it still said some problems detected. Is this normal?

My operating system is MacOS Monterey 12.4 with Apple M1 Pro chip.

**Comment by jeromelaban** [comment]
Thanks for the report. Can you run with the [`--verbose`](https://github.com/unoplatform/uno.check/blob/main/doc/using-uno-check.md#troubleshooting) option and post the log?

**Comment by Wave-SYJ** [comment]
> Thanks for the report. Can you run with the [`--verbose`](https://github.com/unoplatform/uno.check/blob/main/doc/using-uno-check.md#troubleshooting) option and post the log?

Yes. The log is:
`
❯ uno-check --verbose

 
           ╓╣╜"╙╬╖
         ╓╣`     "╣╗
       ,@Ñ╜╩╬╗     ╙▒Ñ%,
     ╓╬╝     ]╣╦   ╓▓  ╙╣╖
    ╬╝     ,@╜  ╚@╬╜     ▒
    ╬╗   ,╣╜ ╝@╦╣`     ╓╣╜
     ╙╬╦ ▒     ╙@╖   ╓╣╜
        ╙╝@      "╙╣▒
           ╚h    ,@╝
             ╙Ñ@Ñ╜
 
 
                                         _                     _                                                                                                        
  _   _   _ __     ___             ___  | |__     ___    ___  | | __                                                                                                    
 | | | | | '_ \   / _ \   _____   / __| | '_ \   / _ \  / __| | |/ /                                                                                                    
 | |_| | | | | | | (_) | |_____| | (__  | | | | |  __/ | (__  |   <                                                                                                     
  \__,_| |_| |_|  \___/           \___| |_| |_|  \___|  \___| |_|\_\                                                                                                    
                                                                                                                                                                        
🚑 Uno Platform Check v1.4.2.0 💉
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
This tool will check your Uno Platform development environment.
If problems are detected, it will offer the option to try and fix them for you, or suggest a way to fix them yourself.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
⏳ Synchronizing configuration...Loading Manifest from: https://raw.githubusercontent.com/unoplatform/uno.check/b2c2358e9f5b0ba12048541c8331b19f82a34edd/manifests/uno.ui.manifest.json
Required Version: 1.2.0
Current Version: 1.4.2.0
 ok
⏳ Scheduling appointments...SetEnvironmentVariable: DOTNET_ROOT=/usr/local/share/dotnet
SetEnvironmentVariable: DOTNET_ROOT=/usr/local/share/dotnet
 ok

🔎 OpenJDK 11.0 Checkup...
ValidateAndroidSdkLocation: ``, result=False
ValidateAndroidSdkLocation: ``, result=False
ValidateAndroidSdkLocation: `/Users/seawave/Library/Android/sdk`, result=True
ValidateJavaSdkLocation: ``, result=False
ValidateJavaSdkLocation: ``, result=False
ValidateJavaSdkLocation: `/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home`, result=True
ValidateAndroidNdkLocation: ``, result=False
ValidateAndroidNdkLocation: ``, result=False
SHELL: /bin/zsh /var/folders/50/sn3m3bt57dq3pk_tmbv_v4cw0000gn/T/tmpDHr42A.tmp
javac 11.0.10
SHELL: /bin/zsh /var/folders/50/sn3m3bt57dq3pk_tmbv_v4cw0000gn/T/tmp3FgXHI.tmp
javac 11.0.10
  ✔ 11.0.10 (/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home/bin/..)
SetEnvironmentVariable: JAVA_HOME=/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home

🔎 Visual Studio 8.10.0 Checkup...

🔎 Android SDK Checkup...
ValidateAndroidSdkLocation: ``, result=False
ValidateAndroidSdkLocation: ``, result=False
ValidateAndroidSdkLocation: `/Users/seawave/Library/Android/sdk`, result=True
ValidateJavaSdkLocation: `/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home`, result=True
ValidateAndroidNdkLocation: ``, result=False
ValidateAndroidNdkLocation: ``, result=False
SetEnvironmentVariable: ANDROID_SDK_ROOT=/Users/seawave/Library/Android/sdk
SetEnvironmentVariable: ANDROID_HOME=/Users/seawave/Library/Android/sdk
  ✔ emulator (31.2.10)
  ✔ build-tools;32.0.0 (32.0.0)
  ✔ platforms;android-32 (1)
  ✔ system-images;android-31;google_apis;x86_64 (9)
  ✔ platform-tools (33.0.2)
  ✔ cmdline-tools;5.0 (5.0)

🔎 Android Emulator Checkup...
  ✔ Emulator: Android_Emulator_31 found.

🔎 XCode 13.3 Checkup...
SHELL: /bin/zsh /var/folders/50/sn3m3bt57dq3pk_tmbv_v4cw0000gn/T/tmpqQZL0Z.tmp
/Library/Developer/CommandLineTools
System.IO.InvalidDataException: Found invalid data while decoding.
  at DotNetCheck.Checkups.XCodeCheckup.GetSelectedXCode() in /_/UnoCheck/Checkups/XCodeCheckup.cs:98                             
  at DotNetCheck.Checkups.XCodeCheckup.Examine(SharedState history)                                                              
  at DotNetCheck.Cli.CheckCommand.ExecuteAsync(CommandContext context, CheckSettings settings) in /_/UnoCheck/CheckCommand.cs:167

🔎 .NET SDK Checkup...
SetEnvironmentVariable: DOTNET_ROOT=/usr/local/share/dotnet
SHELL: /bin/zsh /var/folders/50/sn3m3bt57dq3pk_tmbv_v4cw0000gn/T/tmp7Uhu2u.tmp
6.0.300 [/usr/local/share/dotnet/sdk]
  ✔ 6.0.300 - /usr/local/share/dotnet/sdk/6.0.300
SetEnvironmentVariable: DOTNET_SDK=/usr/local/share/dotnet/sdk/6.0.300
SetEnvironmentVariable: DOTNET_SDK_VERSION=6.0.300

🔎 .NET SDK - Workload Deduplication Checkup...
SetEnvironmentVariable: DOTNET_ROOT=/usr/local/share/dotnet

🔎 .NET SDK - EnableWorkloadResolver.sentinel Checkup...
  ✔ /usr/local/share/dotnet/sdk/6.0.300/EnableWorkloadResolver.sentinel exists.

🔎 GTK3+ Checkup...

🔎 .NET SDK - Workloads (6.0.300) Checkup...
  ✔ android (Microsoft.NET.Sdk.Android.Manifest-6.0.300 : 32.0.301) installed.
  ✔ ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.300 : 15.4.303) installed.
  ✔ maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300 : 15.4.303) installed.
  ✔ tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.300 : 15.4.303) installed.
  ✔ macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.300 : 12.3.303) installed.
  ✔ wasm-tools (microsoft.net.workload.mono.toolchain-6.0.300 : 6.0.5) installed.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Checkup had Error status: xcode

xcode: Found invalid data while decoding.
🔔 There were one or more problems detected.
Please review the errors and correct them and run uno-check again.

Press Enter to finish...

`

I realized I haven't installed xcode. Maybe this is why my uno-check fails.

**Comment by jeromelaban** [comment]
Indeed, this is why the check fails. It should be reporting in the tooling, though. Thanks for the information!
