### ISSUE TITLE
New version available message and instructions

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno.check#74]
It would be nice if `uno-check` when executed check if there's a new update available and suggested users install it.

Could be something like:

![image](https://user-images.githubusercontent.com/1900897/174654408-085f5653-8e70-4b2e-93a7-2e42eaa2b1d1.png)

**Comment by ajpinedam** [comment]
It'd actually be `dotnet tool update -g uno.check`

**Comment by jeromelaban** [comment]
It was originally the intent of the tool, but stability goes in the way as it makes it harder to roll back to a previous version...

**Comment by ajpinedam** [comment]
Closing as this was already covered in PR https://github.com/unoplatform/uno.check/pull/124
