### ISSUE TITLE
Add validation for long path support

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.check#81]
Validate for the presence of the Windows registry key which [enables long path support](https://github.com/unoplatform/uno/discussions/9370).

The suggestion should also include a mention to reboot once the change has been made.

**Comment by aesteves900** [comment]
@jeromelaban 

The path I`m following is to implement the ITask from Microsoft.Build.FrameworkMicrosoft.Build.Framework and check if the Registry key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem value LongPathsEnabled is enable. If not, display the native windows dialog before checking the permissions and ask the user about to execute elevated and reboot the system.  

If you agree with this path, what is the cs project best to start this ITask from a developer perspective?

**Comment by jeromelaban** [comment]
This is an uno-check feature, not an Uno build task. You will need to implement a checkup similar to the [ones already present](https://github.com/unoplatform/uno.check/tree/main/UnoCheck/Checkups), then implement the required solution, [similar to this one](https://github.com/unoplatform/uno.check/blob/main/UnoCheck/Checkups/AndroidSdkCheckup.cs#L194-L229). The application is already running elevated on windows so there's no interaction needed.
